name: CI Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tool

    steps:
      - uses: actions/checkout@v3
      - name: Run testing suite
        run: make test
